#########################################################################
# Title:         Cloudbox: Cloudplow Role                               #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# - name: Check filebot-monitor service exists
#   stat:
#     path: "/etc/systemd/system/filebot-monitor.service"
#   register: filebot_monitor_service

# - name: Stop existing filebot-monitor service
#   systemd: state=stopped name=filebot-monitor
#   when: filebot-filebot_monitor_service.stat.exists

- name: Create filebot directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - /opt/filebot-test

- name: Clone filebot (custom build)
  git:
    repo: https://{{ bitbucket.user | urlencode }}:{{ bitbucket.pass | urlencode }}@bitbucket.org/whiskaz/fb_build/
    dest: /opt/filebot-test
    version: master
    force: yes
  become: yes
  become_user: "{{user}}"

- name: Check config exists
  stat:
    path: "/opt/filebot-test/bin/monitor.cfg"
  register: filebot_monitor_config

- name: Import Plex Auth Token role
  import_role:
    name: plex_auth_token
  when: plex_account_enabled and not filebot_monitor_config.stat.exists

- name: "Set 'plexconfig' variable"
  set_fact:
    plexconfig: "plex=localhost:{{plex_auth_token}}"
  when: plex_account_enabled and not filebot_monitor_config.stat.exists 

- name: Import default config
  template:
    src: monitor.cfg.js2
    dest: /opt/filebot-test/bin/monitor.cfg
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  when: not filebot_monitor_config.stat.exists

- name: Set monitor.sh as executable
  file:
    path: /opt/filebot-test/bin/monitor.sh
    owner: "{{user}}"
    group: "{{user}}"
    mode: a+x

- name: Set filebot.sh as executable
  file:
    path: /opt/filebot-test/bin/filebot.sh
    owner: "{{user}}"
    group: "{{user}}"
    mode: a+x

- name: Set directory permissions
  file: "path=/opt/filebot-test state=directory owner={{user}} group={{user}} recurse=yes"

# - name: "Create /usr/local/bin symlink"
#   file:
#     src: "/opt/filebot/bin/filebot.sh"
#     dest: "/usr/local/bin/filebot"
#     state: link

# - name: Import filebot-monitor service
#   template:
#     src: filebot-monitor.service.js2
#     dest: /etc/systemd/system/filebot-monitor.service
#     force: yes

# - name: Start filebot-monitor service
#   systemd: state=started name=filebot-monitor daemon_reload=yes enabled=yes
